apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-client-config
  namespace: ns-one
data:
  APP_PORT: "3000"
  APP_NAME: "grpc-client"
  APP_CLIENT_DELAY_MS: "2000"
  DNS_RESOLVER_DELAY_MS: "10000"
  OTEL_RPC_URI: "otel-collector:4317"
  PYROSCOPE_URI: "http://pyroscope:4040"
  EXTERNAL_GRPC: "dns:///grpc-server.ns-one.svc.cluster.local:50051"
  EXTERNAL_HTTP: "http-server-1:3000"
  MONGO_URI: "mongodb://root:mypswd123@host.docker.internal:27017"
  MONGO_DB_NAME: "grafana"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: ns-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: ifundeasy/simple-crud:v1.0.5
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: grpc-client-config
          env:
            - name: APP_MODE
              value: "grpc-client"
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: "25m"
              memory: "16Mi"
            limits:
              cpu: "75m"
              memory: "32Mi"
