apiVersion: v1
kind: ConfigMap
metadata:
  name: http-server-1-config
  namespace: ns-one
data:
  APP_PORT: "3000"
  APP_NAME: "http-server-1"
  APP_CLIENT_DELAY_MS: "200"
  OTEL_RPC_URI: "otel-collector:4317"
  PYROSCOPE_URI: "http://pyroscope:4040"
  EXTERNAL_GRPC: "grpc-server:50051"
  EXTERNAL_HTTP: "http-server-2:3000"
  MONGO_URI: "mongodb://root:mypswd123@host.docker.internal:27017"
  MONGO_DB_NAME: "grafana"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-1
  namespace: ns-one
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server-1
  template:
    metadata:
      labels:
        app: http-server-1
    spec:
      containers:
        - name: http-server-1
          image: ifundeasy/simple-crud:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: http-server-1-config
          env:
            - name: APP_MODE
              value: "http"
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-1
  namespace: ns-one
spec:
  selector:
    app: http-server-1
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-server-1-hpa
  namespace: ns-one
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server-1
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
