apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-server-config
  namespace: ns-one
data:
  APP_PORT: "50051"
  APP_NAME: "grpc-server"
  APP_CLIENT_DELAY_MS: "200"
  OTEL_RPC_URI: "otel-collector:4317"
  PYROSCOPE_URI: "http://pyroscope:4040"
  EXTERNAL_GRPC: "grpc-server:50051"
  EXTERNAL_HTTP: "http-server-1:3000"
  # # With $ ngrok tcp 27017
  # MONGO_URI: "mongodb://root:mypswd123@0.tcp.ap.ngrok.io:19227"
  MONGO_URI: "mongodb://root:mypswd123@host.docker.internal:27017"
  MONGO_DB_NAME: "grafana"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: ns-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: ifundeasy/simple-crud:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: grpc-server-config
          env:
            - name: APP_MODE
              value: "grpc"
          ports:
            - name: grpc
              containerPort: 50051
          resources:
            requests:
              cpu: "100m"
              memory: "24Mi"
            limits:
              cpu: "400m"
              memory: "48Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: ns-one
spec:
  # type: ClusterIP
  clusterIP: None  # 👈 HEADLESS mode
  selector:
    app: grpc-server
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-server-hpa
  namespace: ns-one
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-server
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
